INSERT INTO CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES
(1000, 'USD', 'INR', 65,'');
INSERT INTO CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES
(1001, 'EUR', 'INR', 75,'');
INSERT INTO CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES
(1003, 'AUD', 'INR', 25,'');
